export const exceptionErrorNames = {
  'Bad Request': 'Неверный Запрос',
  Unauthorized: 'Неавторизованный',
  'Not Found': 'Не Найдено',
  Forbidden: 'Запрещено',
  'Not Acceptable': 'Неприемлемо',
  'Request Timeout': 'Тайм-аут Запроса',
  Conflict: 'Конфликт',
  Gone: 'Удалено',
  'HTTP Version Not Supported': 'Версия HTTP Не Поддерживается',
  'Payload Too Large': 'Слишком Большой Объём Запроса',
  'Unsupported Media Type': 'Неподдерживаемый Тип Данных',
  'Unprocessable Entity': 'Необрабатываемый Объект',
  'Internal Server Error': 'Внутренняя Ошибка Сервера',
  'Not Implemented': 'Не Реализовано',
  "I'm a Teapot": 'Я – Чайник',
  'Method Not Allowed': 'Метод Не Разрешен',
  'Bad Gateway': 'Плохой Шлюз',
  'Service Unavailable': 'Сервис Недоступен',
  'Gateway Timeout': 'Тайм-аут Шлюза',
  'Precondition Failed': 'Условие Не Соблюдено',
  'Misdirected Request': 'Неправильно Направленный Запрос',
  'Too Many Requests': 'Слишком Много Запросов',
  'Failed Dependency': 'Сбой Зависимости',
};
